// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game/world/world.proto

package world

import (
	nodes "OnlineGame/pkg/pb/go/game/world/nodes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type World struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MinPlayers      uint32                 `protobuf:"varint,1,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers      uint32                 `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	PlayerIdNGidMap map[uint32]uint32      `protobuf:"bytes,3,rep,name=player_id_n_gid_map,json=playerIdNGidMap,proto3" json:"player_id_n_gid_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Nodes           map[uint32]*nodes.Node `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeEdges       []*nodes.NodeEdge      `protobuf:"bytes,5,rep,name=node_edges,json=nodeEdges,proto3" json:"node_edges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *World) Reset() {
	*x = World{}
	mi := &file_game_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *World) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*World) ProtoMessage() {}

func (x *World) ProtoReflect() protoreflect.Message {
	mi := &file_game_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use World.ProtoReflect.Descriptor instead.
func (*World) Descriptor() ([]byte, []int) {
	return file_game_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *World) GetMinPlayers() uint32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *World) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *World) GetPlayerIdNGidMap() map[uint32]uint32 {
	if x != nil {
		return x.PlayerIdNGidMap
	}
	return nil
}

func (x *World) GetNodes() map[uint32]*nodes.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *World) GetNodeEdges() []*nodes.NodeEdge {
	if x != nil {
		return x.NodeEdges
	}
	return nil
}

var File_game_world_world_proto protoreflect.FileDescriptor

const file_game_world_world_proto_rawDesc = "" +
	"\n" +
	"\x16game/world/world.proto\x12\x05world\x1a\x1cgame/world/nodes/nodes.proto\"\x84\x03\n" +
	"\x05World\x12\x1f\n" +
	"\vmin_players\x18\x01 \x01(\rR\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\rR\n" +
	"maxPlayers\x12O\n" +
	"\x13player_id_n_gid_map\x18\x03 \x03(\v2!.world.World.PlayerIdNGidMapEntryR\x0fplayerIdNGidMap\x12-\n" +
	"\x05nodes\x18\x04 \x03(\v2\x17.world.World.NodesEntryR\x05nodes\x12.\n" +
	"\n" +
	"node_edges\x18\x05 \x03(\v2\x0f.nodes.NodeEdgeR\tnodeEdges\x1aB\n" +
	"\x14PlayerIdNGidMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aE\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.nodes.NodeR\x05value:\x028\x01B!Z\x1fOnlineGame/pkg/pb/go/game/worldb\x06proto3"

var (
	file_game_world_world_proto_rawDescOnce sync.Once
	file_game_world_world_proto_rawDescData []byte
)

func file_game_world_world_proto_rawDescGZIP() []byte {
	file_game_world_world_proto_rawDescOnce.Do(func() {
		file_game_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_world_world_proto_rawDesc), len(file_game_world_world_proto_rawDesc)))
	})
	return file_game_world_world_proto_rawDescData
}

var file_game_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_world_world_proto_goTypes = []any{
	(*World)(nil),          // 0: world.World
	nil,                    // 1: world.World.PlayerIdNGidMapEntry
	nil,                    // 2: world.World.NodesEntry
	(*nodes.NodeEdge)(nil), // 3: nodes.NodeEdge
	(*nodes.Node)(nil),     // 4: nodes.Node
}
var file_game_world_world_proto_depIdxs = []int32{
	1, // 0: world.World.player_id_n_gid_map:type_name -> world.World.PlayerIdNGidMapEntry
	2, // 1: world.World.nodes:type_name -> world.World.NodesEntry
	3, // 2: world.World.node_edges:type_name -> nodes.NodeEdge
	4, // 3: world.World.NodesEntry.value:type_name -> nodes.Node
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_world_world_proto_init() }
func file_game_world_world_proto_init() {
	if File_game_world_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_world_world_proto_rawDesc), len(file_game_world_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_world_world_proto_goTypes,
		DependencyIndexes: file_game_world_world_proto_depIdxs,
		MessageInfos:      file_game_world_world_proto_msgTypes,
	}.Build()
	File_game_world_world_proto = out.File
	file_game_world_world_proto_goTypes = nil
	file_game_world_world_proto_depIdxs = nil
}
