// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game/input.proto

package game

import (
	nodes "OnlineGame/pkg/pb/go/game/world/nodes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InputMessage_Action
	Payload       isInputMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_game_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_game_input_proto_rawDescGZIP(), []int{0}
}

func (x *InputMessage) GetPayload() isInputMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InputMessage) GetAction() *ActionInputMessage {
	if x != nil {
		if x, ok := x.Payload.(*InputMessage_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isInputMessage_Payload interface {
	isInputMessage_Payload()
}

type InputMessage_Action struct {
	Action *ActionInputMessage `protobuf:"bytes,1,opt,name=action,proto3,oneof"`
}

func (*InputMessage_Action) isInputMessage_Payload() {}

type ActionInputMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ActionInputMessage_SendArmy
	//	*ActionInputMessage_UpdateNodeType
	//	*ActionInputMessage_SetAlwaysSendArmy
	Payload       isActionInputMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionInputMessage) Reset() {
	*x = ActionInputMessage{}
	mi := &file_game_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionInputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInputMessage) ProtoMessage() {}

func (x *ActionInputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInputMessage.ProtoReflect.Descriptor instead.
func (*ActionInputMessage) Descriptor() ([]byte, []int) {
	return file_game_input_proto_rawDescGZIP(), []int{1}
}

func (x *ActionInputMessage) GetPayload() isActionInputMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ActionInputMessage) GetSendArmy() *SendArmyAction {
	if x != nil {
		if x, ok := x.Payload.(*ActionInputMessage_SendArmy); ok {
			return x.SendArmy
		}
	}
	return nil
}

func (x *ActionInputMessage) GetUpdateNodeType() *UpdateNodeTypeAction {
	if x != nil {
		if x, ok := x.Payload.(*ActionInputMessage_UpdateNodeType); ok {
			return x.UpdateNodeType
		}
	}
	return nil
}

func (x *ActionInputMessage) GetSetAlwaysSendArmy() *SetAlwaysSendArmyAction {
	if x != nil {
		if x, ok := x.Payload.(*ActionInputMessage_SetAlwaysSendArmy); ok {
			return x.SetAlwaysSendArmy
		}
	}
	return nil
}

type isActionInputMessage_Payload interface {
	isActionInputMessage_Payload()
}

type ActionInputMessage_SendArmy struct {
	SendArmy *SendArmyAction `protobuf:"bytes,1,opt,name=send_army,json=sendArmy,proto3,oneof"`
}

type ActionInputMessage_UpdateNodeType struct {
	UpdateNodeType *UpdateNodeTypeAction `protobuf:"bytes,2,opt,name=update_node_type,json=updateNodeType,proto3,oneof"`
}

type ActionInputMessage_SetAlwaysSendArmy struct {
	SetAlwaysSendArmy *SetAlwaysSendArmyAction `protobuf:"bytes,3,opt,name=set_always_send_army,json=setAlwaysSendArmy,proto3,oneof"`
}

func (*ActionInputMessage_SendArmy) isActionInputMessage_Payload() {}

func (*ActionInputMessage_UpdateNodeType) isActionInputMessage_Payload() {}

func (*ActionInputMessage_SetAlwaysSendArmy) isActionInputMessage_Payload() {}

type SendArmyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	HeadingFromId uint64                 `protobuf:"varint,2,opt,name=heading_from_id,json=headingFromId,proto3" json:"heading_from_id,omitempty"`
	HeadingToId   uint64                 `protobuf:"varint,3,opt,name=heading_to_id,json=headingToId,proto3" json:"heading_to_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendArmyAction) Reset() {
	*x = SendArmyAction{}
	mi := &file_game_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendArmyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendArmyAction) ProtoMessage() {}

func (x *SendArmyAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendArmyAction.ProtoReflect.Descriptor instead.
func (*SendArmyAction) Descriptor() ([]byte, []int) {
	return file_game_input_proto_rawDescGZIP(), []int{2}
}

func (x *SendArmyAction) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SendArmyAction) GetHeadingFromId() uint64 {
	if x != nil {
		return x.HeadingFromId
	}
	return 0
}

func (x *SendArmyAction) GetHeadingToId() uint64 {
	if x != nil {
		return x.HeadingToId
	}
	return 0
}

type UpdateNodeTypeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NewType       nodes.NodeType         `protobuf:"varint,2,opt,name=new_type,json=newType,proto3,enum=nodes.NodeType" json:"new_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeTypeAction) Reset() {
	*x = UpdateNodeTypeAction{}
	mi := &file_game_input_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeTypeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeTypeAction) ProtoMessage() {}

func (x *UpdateNodeTypeAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_input_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeTypeAction.ProtoReflect.Descriptor instead.
func (*UpdateNodeTypeAction) Descriptor() ([]byte, []int) {
	return file_game_input_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNodeTypeAction) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UpdateNodeTypeAction) GetNewType() nodes.NodeType {
	if x != nil {
		return x.NewType
	}
	return nodes.NodeType(0)
}

type SetAlwaysSendArmyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    uint64                 `protobuf:"varint,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      uint64                 `protobuf:"varint,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Mode          bool                   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlwaysSendArmyAction) Reset() {
	*x = SetAlwaysSendArmyAction{}
	mi := &file_game_input_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlwaysSendArmyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlwaysSendArmyAction) ProtoMessage() {}

func (x *SetAlwaysSendArmyAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_input_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlwaysSendArmyAction.ProtoReflect.Descriptor instead.
func (*SetAlwaysSendArmyAction) Descriptor() ([]byte, []int) {
	return file_game_input_proto_rawDescGZIP(), []int{4}
}

func (x *SetAlwaysSendArmyAction) GetFromNodeId() uint64 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *SetAlwaysSendArmyAction) GetToNodeId() uint64 {
	if x != nil {
		return x.ToNodeId
	}
	return 0
}

func (x *SetAlwaysSendArmyAction) GetMode() bool {
	if x != nil {
		return x.Mode
	}
	return false
}

var File_game_input_proto protoreflect.FileDescriptor

const file_game_input_proto_rawDesc = "" +
	"\n" +
	"\x10game/input.proto\x12\x04game\x1a\x1cgame/world/nodes/nodes.proto\"M\n" +
	"\fInputMessage\x122\n" +
	"\x06action\x18\x01 \x01(\v2\x18.game.ActionInputMessageH\x00R\x06actionB\t\n" +
	"\apayload\"\xee\x01\n" +
	"\x12ActionInputMessage\x123\n" +
	"\tsend_army\x18\x01 \x01(\v2\x14.game.SendArmyActionH\x00R\bsendArmy\x12F\n" +
	"\x10update_node_type\x18\x02 \x01(\v2\x1a.game.UpdateNodeTypeActionH\x00R\x0eupdateNodeType\x12P\n" +
	"\x14set_always_send_army\x18\x03 \x01(\v2\x1d.game.SetAlwaysSendArmyActionH\x00R\x11setAlwaysSendArmyB\t\n" +
	"\apayload\"r\n" +
	"\x0eSendArmyAction\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12&\n" +
	"\x0fheading_from_id\x18\x02 \x01(\x04R\rheadingFromId\x12\"\n" +
	"\rheading_to_id\x18\x03 \x01(\x04R\vheadingToId\"[\n" +
	"\x14UpdateNodeTypeAction\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12*\n" +
	"\bnew_type\x18\x02 \x01(\x0e2\x0f.nodes.NodeTypeR\anewType\"m\n" +
	"\x17SetAlwaysSendArmyAction\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\x04R\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\x04R\btoNodeId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\bR\x04modeB\x1bZ\x19OnlineGame/pkg/pb/go/gameb\x06proto3"

var (
	file_game_input_proto_rawDescOnce sync.Once
	file_game_input_proto_rawDescData []byte
)

func file_game_input_proto_rawDescGZIP() []byte {
	file_game_input_proto_rawDescOnce.Do(func() {
		file_game_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_input_proto_rawDesc), len(file_game_input_proto_rawDesc)))
	})
	return file_game_input_proto_rawDescData
}

var file_game_input_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_input_proto_goTypes = []any{
	(*InputMessage)(nil),            // 0: game.InputMessage
	(*ActionInputMessage)(nil),      // 1: game.ActionInputMessage
	(*SendArmyAction)(nil),          // 2: game.SendArmyAction
	(*UpdateNodeTypeAction)(nil),    // 3: game.UpdateNodeTypeAction
	(*SetAlwaysSendArmyAction)(nil), // 4: game.SetAlwaysSendArmyAction
	(nodes.NodeType)(0),             // 5: nodes.NodeType
}
var file_game_input_proto_depIdxs = []int32{
	1, // 0: game.InputMessage.action:type_name -> game.ActionInputMessage
	2, // 1: game.ActionInputMessage.send_army:type_name -> game.SendArmyAction
	3, // 2: game.ActionInputMessage.update_node_type:type_name -> game.UpdateNodeTypeAction
	4, // 3: game.ActionInputMessage.set_always_send_army:type_name -> game.SetAlwaysSendArmyAction
	5, // 4: game.UpdateNodeTypeAction.new_type:type_name -> nodes.NodeType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_game_input_proto_init() }
func file_game_input_proto_init() {
	if File_game_input_proto != nil {
		return
	}
	file_game_input_proto_msgTypes[0].OneofWrappers = []any{
		(*InputMessage_Action)(nil),
	}
	file_game_input_proto_msgTypes[1].OneofWrappers = []any{
		(*ActionInputMessage_SendArmy)(nil),
		(*ActionInputMessage_UpdateNodeType)(nil),
		(*ActionInputMessage_SetAlwaysSendArmy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_input_proto_rawDesc), len(file_game_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_input_proto_goTypes,
		DependencyIndexes: file_game_input_proto_depIdxs,
		MessageInfos:      file_game_input_proto_msgTypes,
	}.Build()
	File_game_input_proto = out.File
	file_game_input_proto_goTypes = nil
	file_game_input_proto_depIdxs = nil
}
