// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game/output.proto

package game

import (
	world "OnlineGame/pkg/pb/go/game/world"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OutputMessage_Tick
	//	*OutputMessage_Notification
	//	*OutputMessage_ActionOutputMessage
	Payload       isOutputMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputMessage) Reset() {
	*x = OutputMessage{}
	mi := &file_game_output_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessage) ProtoMessage() {}

func (x *OutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_output_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessage.ProtoReflect.Descriptor instead.
func (*OutputMessage) Descriptor() ([]byte, []int) {
	return file_game_output_proto_rawDescGZIP(), []int{0}
}

func (x *OutputMessage) GetPayload() isOutputMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutputMessage) GetTick() *Tick {
	if x != nil {
		if x, ok := x.Payload.(*OutputMessage_Tick); ok {
			return x.Tick
		}
	}
	return nil
}

func (x *OutputMessage) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Payload.(*OutputMessage_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *OutputMessage) GetActionOutputMessage() *ActionOutputMessage {
	if x != nil {
		if x, ok := x.Payload.(*OutputMessage_ActionOutputMessage); ok {
			return x.ActionOutputMessage
		}
	}
	return nil
}

type isOutputMessage_Payload interface {
	isOutputMessage_Payload()
}

type OutputMessage_Tick struct {
	Tick *Tick `protobuf:"bytes,1,opt,name=tick,proto3,oneof"`
}

type OutputMessage_Notification struct {
	Notification *Notification `protobuf:"bytes,3,opt,name=notification,proto3,oneof"`
}

type OutputMessage_ActionOutputMessage struct {
	ActionOutputMessage *ActionOutputMessage `protobuf:"bytes,2,opt,name=action_output_message,json=actionOutputMessage,proto3,oneof"`
}

func (*OutputMessage_Tick) isOutputMessage_Payload() {}

func (*OutputMessage_Notification) isOutputMessage_Payload() {}

func (*OutputMessage_ActionOutputMessage) isOutputMessage_Payload() {}

type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       uint32                 `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	CurrentTps    float32                `protobuf:"fixed32,2,opt,name=current_tps,json=currentTps,proto3" json:"current_tps,omitempty"`
	World         *world.World           `protobuf:"bytes,3,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_game_output_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_game_output_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_game_output_proto_rawDescGZIP(), []int{1}
}

func (x *Tick) GetMatchId() uint32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Tick) GetCurrentTps() float32 {
	if x != nil {
		return x.CurrentTps
	}
	return 0
}

func (x *Tick) GetWorld() *world.World {
	if x != nil {
		return x.World
	}
	return nil
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MatchId        uint64                 `protobuf:"varint,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerId       uint64                 `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerUsername string                 `protobuf:"bytes,5,opt,name=player_username,json=playerUsername,proto3" json:"player_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_game_output_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_game_output_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_game_output_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Notification) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Notification) GetPlayerUsername() string {
	if x != nil {
		return x.PlayerUsername
	}
	return ""
}

type ActionOutputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionOutputMessage) Reset() {
	*x = ActionOutputMessage{}
	mi := &file_game_output_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionOutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionOutputMessage) ProtoMessage() {}

func (x *ActionOutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_output_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionOutputMessage.ProtoReflect.Descriptor instead.
func (*ActionOutputMessage) Descriptor() ([]byte, []int) {
	return file_game_output_proto_rawDescGZIP(), []int{3}
}

func (x *ActionOutputMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionOutputMessage) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_game_output_proto protoreflect.FileDescriptor

const file_game_output_proto_rawDesc = "" +
	"\n" +
	"\x11game/output.proto\x12\x04game\x1a\x16game/world/world.proto\"\xc7\x01\n" +
	"\rOutputMessage\x12 \n" +
	"\x04tick\x18\x01 \x01(\v2\n" +
	".game.TickH\x00R\x04tick\x128\n" +
	"\fnotification\x18\x03 \x01(\v2\x12.game.NotificationH\x00R\fnotification\x12O\n" +
	"\x15action_output_message\x18\x02 \x01(\v2\x19.game.ActionOutputMessageH\x00R\x13actionOutputMessageB\t\n" +
	"\apayload\"f\n" +
	"\x04Tick\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\rR\amatchId\x12\x1f\n" +
	"\vcurrent_tps\x18\x02 \x01(\x02R\n" +
	"currentTps\x12\"\n" +
	"\x05world\x18\x03 \x01(\v2\f.world.WorldR\x05world\"\x9d\x01\n" +
	"\fNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\x04R\amatchId\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\x04R\bplayerId\x12'\n" +
	"\x0fplayer_username\x18\x05 \x01(\tR\x0eplayerUsername\"G\n" +
	"\x13ActionOutputMessage\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetailsB\x1bZ\x19OnlineGame/pkg/pb/go/gameb\x06proto3"

var (
	file_game_output_proto_rawDescOnce sync.Once
	file_game_output_proto_rawDescData []byte
)

func file_game_output_proto_rawDescGZIP() []byte {
	file_game_output_proto_rawDescOnce.Do(func() {
		file_game_output_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_output_proto_rawDesc), len(file_game_output_proto_rawDesc)))
	})
	return file_game_output_proto_rawDescData
}

var file_game_output_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_output_proto_goTypes = []any{
	(*OutputMessage)(nil),       // 0: game.OutputMessage
	(*Tick)(nil),                // 1: game.Tick
	(*Notification)(nil),        // 2: game.Notification
	(*ActionOutputMessage)(nil), // 3: game.ActionOutputMessage
	(*world.World)(nil),         // 4: world.World
}
var file_game_output_proto_depIdxs = []int32{
	1, // 0: game.OutputMessage.tick:type_name -> game.Tick
	2, // 1: game.OutputMessage.notification:type_name -> game.Notification
	3, // 2: game.OutputMessage.action_output_message:type_name -> game.ActionOutputMessage
	4, // 3: game.Tick.world:type_name -> world.World
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_output_proto_init() }
func file_game_output_proto_init() {
	if File_game_output_proto != nil {
		return
	}
	file_game_output_proto_msgTypes[0].OneofWrappers = []any{
		(*OutputMessage_Tick)(nil),
		(*OutputMessage_Notification)(nil),
		(*OutputMessage_ActionOutputMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_output_proto_rawDesc), len(file_game_output_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_output_proto_goTypes,
		DependencyIndexes: file_game_output_proto_depIdxs,
		MessageInfos:      file_game_output_proto_msgTypes,
	}.Build()
	File_game_output_proto = out.File
	file_game_output_proto_goTypes = nil
	file_game_output_proto_depIdxs = nil
}
