// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game/world/nodes/nodes.proto

package nodes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_DefaultNodeType    NodeType = 0
	NodeType_ProductionNodeType NodeType = 1
	NodeType_FortressNodeType   NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "DefaultNodeType",
		1: "ProductionNodeType",
		3: "FortressNodeType",
	}
	NodeType_value = map[string]int32{
		"DefaultNodeType":    0,
		"ProductionNodeType": 1,
		"FortressNodeType":   3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_world_nodes_nodes_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_game_world_nodes_nodes_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_game_world_nodes_nodes_proto_rawDescGZIP(), []int{0}
}

type Node struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PosX                   int32                  `protobuf:"varint,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                   int32                  `protobuf:"varint,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	OwnerId                uint64                 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Type                   NodeType               `protobuf:"varint,5,opt,name=type,proto3,enum=nodes.NodeType" json:"type,omitempty"`
	Shield                 uint32                 `protobuf:"varint,6,opt,name=shield,proto3" json:"shield,omitempty"`
	Value                  uint32                 `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	IsAlwaysSendArmy       bool                   `protobuf:"varint,8,opt,name=is_always_send_army,json=isAlwaysSendArmy,proto3" json:"is_always_send_army,omitempty"`
	AlwaysSendArmyToNodeId uint64                 `protobuf:"varint,9,opt,name=always_send_army_to_node_id,json=alwaysSendArmyToNodeId,proto3" json:"always_send_army_to_node_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_game_world_nodes_nodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_game_world_nodes_nodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_game_world_nodes_nodes_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *Node) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *Node) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_DefaultNodeType
}

func (x *Node) GetShield() uint32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *Node) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Node) GetIsAlwaysSendArmy() bool {
	if x != nil {
		return x.IsAlwaysSendArmy
	}
	return false
}

func (x *Node) GetAlwaysSendArmyToNodeId() uint64 {
	if x != nil {
		return x.AlwaysSendArmyToNodeId
	}
	return 0
}

type Army struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos           uint32                 `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	NodeEdgeId    uint64                 `protobuf:"varint,3,opt,name=node_edge_id,json=nodeEdgeId,proto3" json:"node_edge_id,omitempty"`
	HeadingFromId uint64                 `protobuf:"varint,4,opt,name=heading_from_id,json=headingFromId,proto3" json:"heading_from_id,omitempty"`
	HeadingToId   uint64                 `protobuf:"varint,5,opt,name=heading_to_id,json=headingToId,proto3" json:"heading_to_id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Value         uint32                 `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Army) Reset() {
	*x = Army{}
	mi := &file_game_world_nodes_nodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Army) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Army) ProtoMessage() {}

func (x *Army) ProtoReflect() protoreflect.Message {
	mi := &file_game_world_nodes_nodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Army.ProtoReflect.Descriptor instead.
func (*Army) Descriptor() ([]byte, []int) {
	return file_game_world_nodes_nodes_proto_rawDescGZIP(), []int{1}
}

func (x *Army) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Army) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *Army) GetNodeEdgeId() uint64 {
	if x != nil {
		return x.NodeEdgeId
	}
	return 0
}

func (x *Army) GetHeadingFromId() uint64 {
	if x != nil {
		return x.HeadingFromId
	}
	return 0
}

func (x *Army) GetHeadingToId() uint64 {
	if x != nil {
		return x.HeadingToId
	}
	return 0
}

func (x *Army) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Army) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NodeEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	N1Id          uint64                 `protobuf:"varint,2,opt,name=n1_id,json=n1Id,proto3" json:"n1_id,omitempty"`
	N2Id          uint64                 `protobuf:"varint,3,opt,name=n2_id,json=n2Id,proto3" json:"n2_id,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Armies        []*Army                `protobuf:"bytes,5,rep,name=armies,proto3" json:"armies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEdge) Reset() {
	*x = NodeEdge{}
	mi := &file_game_world_nodes_nodes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEdge) ProtoMessage() {}

func (x *NodeEdge) ProtoReflect() protoreflect.Message {
	mi := &file_game_world_nodes_nodes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEdge.ProtoReflect.Descriptor instead.
func (*NodeEdge) Descriptor() ([]byte, []int) {
	return file_game_world_nodes_nodes_proto_rawDescGZIP(), []int{2}
}

func (x *NodeEdge) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeEdge) GetN1Id() uint64 {
	if x != nil {
		return x.N1Id
	}
	return 0
}

func (x *NodeEdge) GetN2Id() uint64 {
	if x != nil {
		return x.N2Id
	}
	return 0
}

func (x *NodeEdge) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *NodeEdge) GetArmies() []*Army {
	if x != nil {
		return x.Armies
	}
	return nil
}

var File_game_world_nodes_nodes_proto protoreflect.FileDescriptor

const file_game_world_nodes_nodes_proto_rawDesc = "" +
	"\n" +
	"\x1cgame/world/nodes/nodes.proto\x12\x05nodes\"\x9a\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x05R\x04posY\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x04R\aownerId\x12#\n" +
	"\x04type\x18\x05 \x01(\x0e2\x0f.nodes.NodeTypeR\x04type\x12\x16\n" +
	"\x06shield\x18\x06 \x01(\rR\x06shield\x12\x14\n" +
	"\x05value\x18\a \x01(\rR\x05value\x12-\n" +
	"\x13is_always_send_army\x18\b \x01(\bR\x10isAlwaysSendArmy\x12;\n" +
	"\x1balways_send_army_to_node_id\x18\t \x01(\x04R\x16alwaysSendArmyToNodeId\"\xc7\x01\n" +
	"\x04Army\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03pos\x18\x02 \x01(\rR\x03pos\x12 \n" +
	"\fnode_edge_id\x18\x03 \x01(\x04R\n" +
	"nodeEdgeId\x12&\n" +
	"\x0fheading_from_id\x18\x04 \x01(\x04R\rheadingFromId\x12\"\n" +
	"\rheading_to_id\x18\x05 \x01(\x04R\vheadingToId\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\x04R\aownerId\x12\x14\n" +
	"\x05value\x18\a \x01(\rR\x05value\"\x81\x01\n" +
	"\bNodeEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x13\n" +
	"\x05n1_id\x18\x02 \x01(\x04R\x04n1Id\x12\x13\n" +
	"\x05n2_id\x18\x03 \x01(\x04R\x04n2Id\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\x12#\n" +
	"\x06armies\x18\x05 \x03(\v2\v.nodes.ArmyR\x06armies*M\n" +
	"\bNodeType\x12\x13\n" +
	"\x0fDefaultNodeType\x10\x00\x12\x16\n" +
	"\x12ProductionNodeType\x10\x01\x12\x14\n" +
	"\x10FortressNodeType\x10\x03B'Z%OnlineGame/pkg/pb/go/game/world/nodesb\x06proto3"

var (
	file_game_world_nodes_nodes_proto_rawDescOnce sync.Once
	file_game_world_nodes_nodes_proto_rawDescData []byte
)

func file_game_world_nodes_nodes_proto_rawDescGZIP() []byte {
	file_game_world_nodes_nodes_proto_rawDescOnce.Do(func() {
		file_game_world_nodes_nodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_world_nodes_nodes_proto_rawDesc), len(file_game_world_nodes_nodes_proto_rawDesc)))
	})
	return file_game_world_nodes_nodes_proto_rawDescData
}

var file_game_world_nodes_nodes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_world_nodes_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_world_nodes_nodes_proto_goTypes = []any{
	(NodeType)(0),    // 0: nodes.NodeType
	(*Node)(nil),     // 1: nodes.Node
	(*Army)(nil),     // 2: nodes.Army
	(*NodeEdge)(nil), // 3: nodes.NodeEdge
}
var file_game_world_nodes_nodes_proto_depIdxs = []int32{
	0, // 0: nodes.Node.type:type_name -> nodes.NodeType
	2, // 1: nodes.NodeEdge.armies:type_name -> nodes.Army
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_world_nodes_nodes_proto_init() }
func file_game_world_nodes_nodes_proto_init() {
	if File_game_world_nodes_nodes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_world_nodes_nodes_proto_rawDesc), len(file_game_world_nodes_nodes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_world_nodes_nodes_proto_goTypes,
		DependencyIndexes: file_game_world_nodes_nodes_proto_depIdxs,
		EnumInfos:         file_game_world_nodes_nodes_proto_enumTypes,
		MessageInfos:      file_game_world_nodes_nodes_proto_msgTypes,
	}.Build()
	File_game_world_nodes_nodes_proto = out.File
	file_game_world_nodes_nodes_proto_goTypes = nil
	file_game_world_nodes_nodes_proto_depIdxs = nil
}
